feature/lock
andrei-tatar/nora-service pull request #6
Opened 2019-11-05 05:24 UTC by rgerrans

I've tried to make all the changes on the back end to enable the creation of a Lock node. Please let me know if I got everything this time or missed any.

Thanks,

Ron

2019-11-11 00:10 UTC, rgerrans commented
@andrei-tatar I've added a fan as well as the lock to the backend services. When you get a chance to update, I'll start testing both. Thanks

2019-11-11 14:08 UTC, andrei-tatar requested changes
Needs a few changes. Please try to build the code before submitting a pull request.
Also, please use spaces, not tabs.

2019-11-11 14:08 UTC, andrei-tatar commented on src/http/services/execute.service.ts
> +		  case ExecuteCommandTypes.FanSpeed:
shouldn't this be `case ExecuteCommandTypes.SetFanSpeed`? Is it building?

2019-11-11 14:08 UTC, andrei-tatar commented on src/http/services/query.service.ts
> +				state.on - device.state.on;
I don't think the intention here is to substract the `on` properties.

2019-11-11 14:08 UTC, andrei-tatar commented on src/http/services/query.service.ts
> +					state.currentFanSpeedSetting = device.state.currentFanSeedSetting || 'off';
The state seems to be missing `currentFanSeedSetting` property. It seems to only have `availableFanSpeeds`.

2019-11-11 14:08 UTC, andrei-tatar commented on src/models/states/fanspeed.ts
> +     availableFanSpeeds: availableFanSpeeds;
Shouldn't `availableFanSpeeds` be an array? I would also let the node-red plugin to define other values as well.

2019-11-11 14:08 UTC, andrei-tatar commented on src/http/services/sync.service.ts
> +						sync.attributes = { availableFanSpeeds: uniq(device.availableFanSpeeds.join(',')};
from the documentation, availableFanSpeeds is an array of objects that contains name, values, etc.
https://developers.google.com/assistant/smarthome/traits/fanspeed#device-attributes

2019-11-11 14:08 UTC, andrei-tatar commented on src/models/states/lockunlock.ts
> +    on: boolean;
From the documentation, it seems the states are different:
https://developers.google.com/assistant/smarthome/traits/lockunlock#device-states

2019-11-11 14:08 UTC, andrei-tatar commented on src/http/services/query.service.ts
> +				state.isLocked = device.state.isLocked;
`LockUnlockState` is missing these properties.

2019-11-11 14:08 UTC, andrei-tatar commented on src/http/services/execute.service.ts
> +		  case ExecuteCommandTypes.LockUnlock:
`LockUnlock` command should be handled differently. It comes with a `lock` param that should be mapped to `isLocked` state property.
https://developers.google.com/assistant/smarthome/traits/lockunlock#device-commands

2019-11-12 04:15 UTC, rgerrans commented
@andrei-tatar So I took a couple steps back and removed all the fan stuff to just focus on the lock now that i spent the time and think I have a better understanding of how the files interconnect and map to the Google pieces. I also took a stab at fixing the execute.service.ts mapping of the Lock  value.

Can you take a look when you have a chance to see if I'm on the right path?

I tried to build these but got a bunch of errors including reference to '@andrei-tatar/ts-ioc'. so guessing I can't setup a build environment?

Thanks for the patience as I learn this stuff.

2019-11-17 08:19 UTC, andrei-tatar commented
@rgerrans fixed the `execute.service` for the lock and merged it to master with this PR: https://github.com/andrei-tatar/nora-service/pull/9

2019-11-17 08:19 UTC, closed without merging